{% set name = "jinja2-ansible-filters" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jinja2-ansible-filters-{{ version }}.tar.gz
  sha256: 07c10cf44d7073f4f01102ca12d9a2dc31b41d47e4c61ed92ef6a6d2669b356b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - jinja2
    - pyyaml

test:
  imports:
    - jinja2_ansible_filters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/dreamer-labs/libraries/jinja2-ansible-filters
  summary: A port of Ansible's jinja2 filters without requiring ansible core.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haris989
