{% set name = "pvandyken-deprecated" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pvandyken_deprecated-{{ version }}.tar.gz
  sha256: ea174be2fd36495fef0e4818c080eccbc6ec9a8ddc177cb9d859cd0044b1b5b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.8
    - typing-extensions >=3.10.0
    - packaging >=22.0

test:
  imports:
    - pvandyken
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Wrapper to manage deprecations
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haris989
