{% set name = "num2words" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/num2words-{{ version }}.tar.gz
  sha256: 29570bf3ff113f2a7eb508d75bbad19ae6934360d8a5e68ea8ff9ce29f02da9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - num2words
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/savoirfairelinux/num2words
  summary: Modules to convert numbers to words. Easily extensible.
  license: LGPL-2.1
  license_file: COPYING

extra:
  recipe-maintainers:
    - haris989
