{% set name = "nibabel" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nibabel-{{ version }}.tar.gz
  sha256: b6c80b2e728e4bc2b65f1142d9b8d2287a9102a8bf8477e115ef0d8334559975

build:
  skip: true  # [py<38]
  entry_points:
    - nib-conform = nibabel.cmdline.conform:main
    - nib-convert = nibabel.cmdline.convert:main
    - nib-ls = nibabel.cmdline.ls:main
    - nib-dicomfs = nibabel.cmdline.dicomfs:main
    - nib-diff = nibabel.cmdline.diff:main
    - nib-stats = nibabel.cmdline.stats:main
    - nib-nifti-dx = nibabel.cmdline.nifti_dx:main
    - nib-tck2trk = nibabel.cmdline.tck2trk:main
    - nib-trk2tck = nibabel.cmdline.trk2tck:main
    - nib-roi = nibabel.cmdline.roi:main
    - parrec2nii = nibabel.cmdline.parrec2nii:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - numpy >=1.20
    - packaging >=17
    - importlib-resources >=1.3  # [py<39]

test:
  imports:
    - nibabel
  commands:
    - pip check
    - nib-conform --help
    - nib-convert --help
    - nib-ls --help
    - nib-dicomfs --help
    - nib-diff --help
    - nib-stats --help
    - nib-nifti-dx --help
    - nib-tck2trk --help
    - nib-trk2tck --help
    - nib-roi --help
    - parrec2nii --help
  requires:
    - pip

about:
  summary: Access a multitude of neuroimaging data formats
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - haris989
