{% set name = "formulaic" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/formulaic-{{ version }}.tar.gz
  sha256: 25b1e1c8dff73f0b11c0028a6ab350222de6bbc47b316ccb770cec16189cef53

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7.2
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.7.2
    - astor >=0.8
    - cached-property >=1.3.0  # [py<38]
    - graphlib-backport >=1.0.0  # [py<39]
    - interface_meta >=1.2.0
    - numpy >=1.16.5
    - pandas >=1.0
    - scipy >=1.6
    - wrapt >=1.0
    - typing-extensions >=4.2.0

test:
  imports:
    - formulaic
  commands:
    - pip check
  requires:
    - pip

about:
  summary: An implementation of Wilkinson formulas.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haris989
