{% set name = "copier" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copier-{{ version }}.tar.gz
  sha256: 9f68afbe3ae2776e61ec8b1cf35743376abd47630e3a81f21e2ffb6dd537a66f

build:
  entry_points:
    - copier = copier.__main__:copier_app_run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.8,<4.0
    - colorama >=0.4.3
    - decorator >=5.1.1
    - dunamai >=1.7.0
    - funcy >=1.17
    - jinja2 >=3.1.1
    - jinja2-ansible-filters >=1.3.1
    - packaging >=23.0
    - pathspec >=0.9.0
    - plumbum >=1.6.9
    - pydantic >=2.0.3
    - pygments >=2.7.1
    - pyyaml >=5.3.1
    - pyyaml-include >=1.2
    - questionary >=1.8.1
    - typing-extensions >=3.7.4,<5.0.0

test:
  imports:
    - copier
  commands:
    - pip check
    - copier --help
  requires:
    - pip

about:
  home: https://github.com/copier-org/copier
  summary: A library for rendering project templates.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haris989
